User.create(display_name: 'Raphaël', email: 'raphael@example.com')
User.create(display_name: 'Apolline', email: 'raphael@example.com')
User.create(display_name: 'Céline', email: 'raphael@example.com')
User.create(display_name: 'Patrick', email: 'raphael@example.com')
User.create(display_name: 'Christine', email: 'raphael@example.com')